export const URL_MENU = '/menu';

export const DATA_MENU = [
  {
    img: '/images/menuPage/goitomthailan.webp',
    title: 'Goi Tom Thai Lan',
    category: 'Goi Tom',
    time: '10-15 min',
    price: '12000',
    isBestSeller: true,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    img: '/images/menuPage/goitomthailan.webp',
    title: 'Goi Tom Thai Lan',
    category: 'Goi Tom',
    time: '10-15 min',
    price: '$12.99',
    isBestSeller: false,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    img: '/images/menuPage/goitomthailan.webp',
    title: 'Goi Tom Thai Lan',
    category: 'Goi Tom',
    time: '10-15 min',
    price: '$12.99',
    isBestSeller: false,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    img: '/images/menuPage/goitomthailan.webp',
    title: 'Goi Tom Thai Lan',
    category: 'Goi Tom',
    time: '10-15 min',
    price: '$12.99',
    isBestSeller: false,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    img: '/images/menuPage/goitomthailan.webp',
    title: 'Goi Tom Thai Lan',
    category: 'Goi Tom',
    time: '10-15 min',
    price: '$12.99',
    isBestSeller: false,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    img: '/images/menuPage/goitomthailan.webp',
    title: 'Goi Tom Thai Lan',
    category: 'Goi Tom',
    time: '10-15 min',
    price: '$12.99',
    isBestSeller: false,
    isSpicy: false,
    isVegetarian: false,
  },
];
