import type { IFeature } from './types';

export const getDataFeature = (t: (key: string) => string): IFeature[] => [
  {
    id: 1,
    img: '/images/landingPage/tomyum.webp',
    title: t('nameTomyum'),
    price: 100000,
    description: 'Súp tôm chua cay truyền thống với sả, lá chanh, ớt',
    isBestSeller: true,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 2,
    img: '/images/menuPage/bo-xao-la-que.jpg',
    title: t('nameTomyum'),
    price: 12000,
    description: 'Súp tôm chua cay truyền thống với sả, lá chanh, ớt',
    isBestSeller: false,
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 3,
    img: '/images/landingPage/tomyum.webp',
    title: t('nameTomyum'),
    price: 100000,
    description: 'Súp tôm chua cay truyền thống với sả, lá chanh, ớt',
    isBestSeller: true,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 4,
    img: '/images/landingPage/tomyum.webp',
    title: t('nameTomyum'),
    price: 100000,
    description: 'Súp tôm chua cay truyền thống với sả, lá chanh, ớt',
    isBestSeller: true,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 5,
    img: '/images/landingPage/tomyum.webp',
    title: t('nameTomyum'),
    price: 100000,
    description: 'Súp tôm chua cay truyền thống với sả, lá chanh, ớt',
    isBestSeller: true,
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 6,
    img: '/images/landingPage/tomyum.webp',
    title: t('nameTomyum'),
    price: 100000,
    description: 'Súp tôm chua cay truyền thống với sả, lá chanh, ớt',
    isBestSeller: true,
    isSpicy: false,
    isVegetarian: false,
  },
];

export const getDataPopular = (t: (key: string) => string): IFeature[] => [
  {
    id: 3,
    img: '/images/landingPage/tomyum.webp',
    title: t('nameTomyum'),
    price: 100000,
    isBestSeller: true,
    isSpicy: false,
    isVegetarian: false,
  },
];
